name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    # Java 17 Setting
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Docker Login
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Make serviceAccountKey.json from firebaseAuth
    - name: make serviceAccountkey.json
      run: |
        touch serviceAccountKey.json
        echo ${{ secrets.FIREBASE_ACCOUNT_KEY }} >> serviceAccountkey.json
      shell: bash
            
    # Springboot Application Build
    - name: Build with Gradle
      run: ./gradlew build -x test

    # Docker Image Build
    - name: Docker Image Build
      run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/gdsc_alert .

    # DockerHub Push
    - name: DockerHub Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gdsc_alert
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted
    steps:

    - name: Docker Pull
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gdsc_alert
    
    - name: Docker Stop
      run: sudo docker stop gdsc_alert 2>/dev/null || true

    - name: Docker Run New
      run: sudo docker run --name gdsc_alert -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/gdsc_alert

    - name: Docker Delete Old Image
      run: sudo docker system prune -f
